server:
  port: 10014
  max-http-header-size: 8192
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.stalary.com
  zipkin:
    base-url: http://zipkin.stalary.com
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.consumer.client: DEBUG # feign日志
com:
  stalary:
    lightmq:
      consumer: true
      order: true
      group: master
      auto: true
      url: lightmq.stalary.com